on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest # FIXME pin OS versions in matrix
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action@v2
        with:
          install-lib: false
      - name: Install NPM dependencies
        run: npm install --legacy-peer-deps
      - name: Generate grammar
        run: tree-sitter generate
      - name: Build grammar
        run: tree-sitter build
